#!/bin/bash
### BEGIN INIT INFO
# Provides:          sensor_receiver_service
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: sensor_receiver init.d script
# Description:       sensor_receiver init.d script
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
DIR=/home/pi/sensor_receiver
COMMCHECK_FILE=bash/commcheck.sh
PYTHON_FILE=src/main.py

DAEMON=$DIR/$PYTHON_FILE
DAEMON_NAME=sensor_receiver
DAEMON_OPT=""
DAEMON_USER=pi
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start(){
    cd $DIR
    sudo bash $COMMCHECK_FILE
    if [ $? -eq 0 ]; then
        sudo chmod 755 $PYTHON_FILE
        sudo nice -n -10 ./$PYTHON_FILE
        exit 0
    fi
}

do_stop(){
    cd $DIR
    #log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    #start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    #log_end_msg $?
    pid=$(ps aux | grep $PYTHON_FILE | grep python | awk '{print $2}')
    if [ -n "$pid" ]; then
        sudo kill -9 $pid
    fi
}

case "$1" in
    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;
esac
exit 0